version: '3.3'

services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.1
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-ollama'
      ENABLE_MODULES: 'text2vec-ollama,generative-ollama'
      CLUSTER_HOSTNAME: 'node1'
    depends_on:
      - ollama


  ollama:
    image: ollama/ollama

    restart: on-failure

  web:
    build: .
    command: >
      sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - weaviate
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  weaviate_data:
